# Generated by Django 3.0.5 on 2020-04-19 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_notification_notificationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_run',
            field=models.BooleanField(default=False),
        ),
    ]
