# Generated by Django 3.0.5 on 2020-04-19 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20200419_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
